apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: homeassistant
    user: grafana
    secureJsonData:
      password: $__env{GRAFANA_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    isDefault: true